server:
    port: 8080
spring:
    application:
        name: API-GATEWAY
    security:
        oauth2:
            client:
                provider:
                    keycloak:
                        issuer-uri: http://localhost:9090/realms/oauthrealm
            
                registration:
                    keycloak:
                        client-id: api-gateway
                        authorization-grant-type: authorization_code
                        scope: openid
            resouceserver:
                jww:
                    issuer-uri: http://localhost:9090/realms/oauthrealm

