server:
    port: 8080
spring:
    application:
        name: API-GATEWAY
    security:
        oauth2:
#            client:
#                provider:
#                    keycloak:
#                        issuer-uri: http://localhost:9090/realms/oauthrealm
#                        user-name-attribute: preferred_username
#
#
#                registration:
#                    keycloak:
#                        client-id: api-gateway
#                        authorization-grant-type: authorization_code
#                        scope: openid
            resourceserver:
                jwt:
                    issuer-uri: http://localhost:9090/realms/oauthrealm





jwt:
    auth:
        converter:
            resource-id: api-gateway
            principle-attribute: preferred_username

